### ISSUE TITLE
DeleteTags doesn't work if tag values have spaces in them

### ISSUE THREAD

**Issue by jmazzitelli** [hawkular/hawkular-client-go#10]
The signature for DeleteTags is:

```
// DeleteTags deletes given tags from the definition
func (c *Client) DeleteTags(t MetricType, id string, tags map[string]string, o ...Modifier) error {
```

Why does it take a map[string]string? You delete tags by name; the value is irrelevent. However, it looks like the code actually builds the DELETE URL with the values which is probably why I'm gettting a error when I try to delete tags:

```
o = prepend(o, c.URL("DELETE", TypeEndpoint(t), SingleMetricEndpoint(id), TagEndpoint(), TagsEndpoint(tags)))
r, err := c.Send(o...)
```

This method should only take a slice of strings (the tag names):

```
// DeleteTags deletes given tags from the definition
func (c *Client) DeleteTags(t MetricType, id string, tags []string, o ...Modifier) error {
```

Or if you don't want to change the signature, just have the code ignore the values and just take the keys of "tags"

**Comment by jmazzitelli** [comment]
FYI: The REST API shows the URL param "tags" should be a "Comma-separated list of tag names" (values should not be in the URL)

http://www.hawkular.org/docs/rest/rest-metrics.html#DELETE__counters__id__tags__tags_

**Comment by jmazzitelli** [comment]
I was getting error 400s using the current master version of DeleteTags. But with PR #11 in place, I am now able to successfully delete tags using the latest Hawkular-Metrics. So I believe that PR fixes the problem.

**Comment by jmazzitelli** [comment]
I can't figure out why client_test.go is passing in TestTagsModification with the original code. But all I can say is the code I was using was broken for me until I added the code in the PR #11

**Comment by burmanm** [comment]
Because this API has changed, depending on the version of Hawkular-Metrics you use. If you use older one (like the one we shipped in Openshift 3.1), you will have to use DeleteTags with values set, otherwise the metrics will not delete them.

**Comment by burmanm** [comment]
HWKMETRICS-385 also says that the backwards compatibility should be preserved.

**Comment by burmanm** [comment]
As far as I can tell, the implementation works correctly, but we can change the signature for the next version instead of relying on the old behavior (which should work, otherwise there's a bug in the Hawkular-Metrics)

**Comment by jmazzitelli** [comment]
I'll go back and try to replicate the error I was getting and see why H-Metrics was reporting an error. My specific code was definitely breaking until I ran with this PR fix.

**Comment by jmazzitelli** [comment]
I found the problem - there were spaces in the tag VALUE - so the DELETE URL looked something like:

http://hmetrics:8080/hawkular/metrics/counters/mnamel/tags/tagname:the value here

This causes a 400 error (notice the spaces in the URL). I can see this in my Chrome REST client, too (I submit that request via my REST client and it gets a 400 also).  If I replace the spaces even with a + (which is wrong, should be %20 technically) and submit that new URL via my Chrome REST client, h-metrics returns a 200/OK status. I guess h-metrics today doesn't care about the value - but for backward compat accepts any value. But because the Go client was sending actual spaces in the tag value, it was caused a bad request to be sent.

**Comment by jmazzitelli** [comment]
Yup - that's the issue for sure. I can replicate in client_test.go by simply changing one of the tag VALUES to include a space - for example change this line:

https://github.com/hawkular/hawkular-client-go/blob/master/metrics/client_test.go#L181

to this:

```
   tags["host"] = "test with space"
```

Notice you put spaces in the tag VALUE (leave the tag names alone - tag names do not have spaces so we can show the space in the VALUE causes the problem).

Run the test and you get this:

```
$ go test -v
...
--- FAIL: TestTagsModification (0.00s)
        Error Trace:    client_test.go:194
    Error:      Expected nil, but got: &metrics.HawkularClientError{msg:"Reply could not be parsed: unexpected end of JSON input", Code:400}
```

**Comment by jmazzitelli** [comment]
BTW: this is why my PR fix works - because it completely strips the entire tag values out of the DELETE URL - so there are no spaces in the URL (since they were in the value and the values are stripped).

Rather than fix it that way, the PR could have simply changed all tag values to a dummy value (like "a") before building the URL

```
// DeleteTags deletes given tags from the definition
func (c *Client) DeleteTags(t MetricType, id string, tags map[string]string, o ...Modifier) error  
{
   for k, _ := range tags {
      tags[k]="a"
   }
   ... the original method code is unchanged here...
```

Since h-metrics doesn't care about the value at all, we can send whatever we want. I have no idea if older versions of H-Metrics also ignore the values. So I'm not sure how best to fix this.

@burmanm  - can you fix this in a way you feel is best for backward compat?

**Comment by jmazzitelli** [comment]
See PR #13 for the alternative fix.

**Comment by jmazzitelli** [comment]
closing this. @burmanm  fixed it here: https://github.com/hawkular/hawkular-client-go/commit/72ea12c211dba93fb6cda6341a0fe3dd89db8a2b#diff-bb7ced84058de3d21d9b13f544a4aa8eR189

I'll create another issue to track the need to add a new API that doesn't require passing in tag values just to delete them.
