### ISSUE TITLE
Support opentracing

### ISSUE THREAD

**Issue by F21** [hawkular/hawkular-client-go#18]
It would be cool if the client can also support opentracing. This would allow go apps to send traces to hawkular.

**Comment by pilhuhn** [comment]
How do you mean? OpenTracing's feature is that you have all the information about where a call "flows through", that information would be lost here.
But of course we could just retrieve the individual values and store them without that flow. Is there a description of the dataformat and how to pull it?

@hawkular/hawkular-apm is probably a project that you would want to look at if using OpenTracing.
@objectiser, @ploffay or @jpkrohling can tell you more

**Comment by objectiser** [comment]
@F21 We do have plans for supporting a Go opentracing provider: https://issues.jboss.org/browse/HWKAPM-789

**Comment by F21** [comment]
@objectiser Thanks! That's what I need. I look forward to implementing it in my apps when it become available 👍

**Comment by burmanm** [comment]
I'll close this one so that there isn't two issues following the same thing. Lets continue in the JIRA.
