### ISSUE TITLE
Please add copyright statement

### ISSUE THREAD

**Issue by onlyjob** [hawkular/hawkular-client-go#3]

**Comment by onlyjob** [comment]
This is required in order to introduce _hawkular-client-go_ to [Debian](http://debian.org) as dependency of Kubernetes.

**Comment by pilhuhn** [comment]
Do you mean as file header? Or in any other format? There is already the LICENSE file here in the repo stating that it is ASL2.

**Comment by onlyjob** [comment]
Copyright statement is a text fragment documenting copyright ownership. It is not the same as license.
Text of the _Apache-2.0_ license contains specific instructions [how to apply the license](../blob/master/LICENSE#L178-L187). Proper application of this license should contain [copyright statement](../blob/master/LICENSE#L189) like 

```
Copyright 2014-2015 Heiko W. Rupp <contact@email.org>
```

and [grant of license](../blob/master/LICENSE#L191-L201).
`README` is the best place to put this information.

Also (please forgive me for pedantic note) it is incorrect to refer to _Apache-2.0_ license as "ASL2". Popular licenses are best referred to by their [SPDX identifiers](https://spdx.org/licenses/).

**Comment by burmanm** [comment]
Hi, would this be suitable for you? Or do you want me to add to each and every file?

**Comment by onlyjob** [comment]
That's perfect, thank you. :)

Adding license grant and copyright statement to every file may be useful in case some files from your project are borrowed and accommodated into another project. In this case it might be useful to include something like `This file is part of hawkular-client-go https://github.com/hawkular/hawkular-client-go`. Some projects prefer to maintain headers but sometimes doing it in `README` is just easier from maintenance prospective.
